export const appConfig = {
  MONTHLY_SUB_PRICE: 5,
  VERIFIED: "VERIFIED",
  PENDING: "PENDING_VALIDATION",
  DOMAIN_EXTENSION: ".brochurify.app",
  MAX_IMAGE_SIZE_MB: 5,
  MAX_IMAGE_COUNT: 50,
  MAX_PROJECT_SIZE_KB: 400,
  FREE_ACC_PROJECT_LIMIT: 3,
  SUB_ACC_PROJECT_LIMIT: 7,
  AWS_CLOUDFRONT_URL: "d23cxyudk0cypl.cloudfront.net",
};
